name: Run Tests

on:
  push:
    branches:
      - main  # Modifica la branch principale se necessario

jobs:
  test:
    runs-on: ubuntu-latest  # Puoi cambiare la piattaforma se necessario

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pyton TestSuite.py
